# Generated by Django 3.0.6 on 2020-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('image5', models.ImageField(upload_to='images/')),
                ('image6', models.ImageField(upload_to='images/')),
                ('image7', models.ImageField(upload_to='images/')),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('text_one', models.TextField()),
                ('text_two', models.TextField()),
                ('text_three', models.TextField()),
                ('ingredients_list', models.TextField(max_length=1500)),
                ('text_four', models.TextField()),
                ('ingredients', models.ManyToManyField(to='basic_app.Ingredients')),
            ],
        ),
    ]
