# Generated by Django 3.0.5 on 2020-06-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='videofile',
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
